export const GET_LOGIN_INFO = "GET_LOGIN_INFO";
export const SET_LOGIN_INFO = "SET_LOGIN_INFO";
export const POST_LOGIN = "POST_LOGIN";
export const POST_USER_LOGIN = "POST_USER_LOGIN";
export const REVOKE_AUTHENTICATION = "REVOKE_AUTHENTICATION";

export const GET_ALL_TWEETS = "GET_ALL_TWEETS";
export const SET_ALL_TWEETS = "SET_ALL_TWEETS";

export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const SET_CURRENT_USER = "SET_CURRENT_USER";