export const GET_LOGIN_INFO = "GET_LOGIN_INFO";
export const SET_LOGIN_INFO = "SET_LOGIN_INFO";
export const POST_LOGIN = "POST_LOGIN";

export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const SET_CURRENT_USER = "SET_CURRENT_USER";