export const GET_LOGIN_INFO = "GET_LOGIN_INFO";
export const SET_LOGIN_INFO = "SET_LOGIN_INFO";
export const POST_LOGIN = "POST_LOGIN";
export const POST_USER_LOGIN = "POST_USER_LOGIN";
export const REVOKE_AUTHENTICATION = "REVOKE_AUTHENTICATION";

export const GET_ACCOUNT_INFO = "GET_ACCOUNT_INFO";
export const SET_ACCOUNT_INFO = "SET_ACCOUNT_INFO";
export const POST_ACCOUNT = "POST_ACCOUNT";
export const PUT_ACCOUNT = "PUT_ACCOUNT";

export const GET_TWEETS_FILTER_TYPE = "GET_TWEETS_FILTER_TYPE";
export const SET_TWEETS_FILTER_TYPE = "SET_TWEETS_FILTER_TYPE";
export const GET_ALL_TWEETS = "GET_ALL_TWEETS";
export const SET_ALL_TWEETS = "SET_ALL_TWEETS";
export const GET_TWEET = "GET_TWEET";
export const SET_TWEET = "SET_TWEET";
export const GET_ONE_USER_TWEETS = "GET_ONE_USER_TWEETS";
export const SET_ONE_USER_TWEETS = "SET_ONE_USER_TWEETS";
export const GET_ONE_USER_REPLIES = "GET_ONE_USER_REPLIES";
export const SET_ONE_USER_REPLIES = "SET_ONE_USER_REPLIES";
export const GET_ONE_USER_LIKES = "GET_ONE_USER_LIKES";
export const SET_ONE_USER_LIKES = "SET_ONE_USER_LIKES";

export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const GET_ALL_USERS = "GET_ALL_USERS";
export const SET_ALL_USERS = "SET_ALL_USERS";

export const GET_NOTIFICATION = "GET_NOTIFICATION";
export const IS_NOTIFICATION_OPEN = "IS_NOTIFICATION_OPEN";
export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export const REMOVE_NOTIFICATION = "REMOVE_NOTIFICATION";